### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by himadrinath** [tpeczek/Lib.Net.Http.WebPush#26]
@tpeczek 

```
Structure.Services.PushServicePushNotificationService: Error: Failed requesting push message delivery to https://fcm.googleapis.com/fcm/send/-------------------------------------------------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at Lib.Net.Http.WebPush.Internals.UrlBase64Converter.FromUrlBase64String(String input) in /_/src/Lib.Net.Http.WebPush/Internals/UrlBase64Converter.cs:line 9
```

exception.StackTrace

   ```
at Lib.Net.Http.WebPush.Internals.UrlBase64Converter.FromUrlBase64String(String input)
   at Lib.Net.Http.WebPush.PushServiceClient.SetContent(HttpRequestMessage pushMessageDeliveryRequest, PushSubscription subscription, PushMessage message)
   at Lib.Net.Http.WebPush.PushServiceClient.PreparePushMessageDeliveryRequest(PushSubscription subscription, PushMessage message, VapidAuthentication authentication, VapidAuthenticationScheme authenticationScheme)
   at Lib.Net.Http.WebPush.PushServiceClient.<RequestPushMessageDeliveryAsync>d__40.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Structure.Services.PushServicePushNotificationService.<SendNotificationAsync>d__6.MoveNext() in C:\Users\abcd\Services\PushServicePushNotificationService.cs:line 46

```

**Comment by himadrinath** [comment]
mybad  i typed key name wrong 'p256dh' not 'P256dh' and 'auth' not 'Auth'

**Comment by tpeczek** [comment]
Hi @himadrinath,

I'm happy you get it working :).

That said, I should probably make the code a little bit tolerant when it comes to case. Also more friendly validation wouldn't hurt. So I'm going to reopen this and keep it at low priority.
